# Generated by Django 3.2.9 on 2021-12-20 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_alter_medicine_medicine_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='available',
        ),
    ]
